<div className={css`
  display: flex;
  align-content: flex-start;
  position: relative;
  width: 20px;
  height: 20px;
  padding: 20px;
  margin: 20px;
  z-index: 10;
  flex-shrink: 1;
  flex-grow: 1;
`} />;